name: KeniSueWho
favicon: null
layout_spectrum: 0.3796
typography_spectrum: 0.32369
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#084780'
    - '#141517'
    - '#e2e9f1'
    - '#b9a699'
    - '#48829d'
  brandStrength: 0.25
  lightness: 0.75
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
